[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Functions 타임아웃은 각 function 파일의 exports.config에서 설정
# netlify.toml에서는 설정하지 않음 (배포 실패 방지)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
